### ISSUE TITLE
Is it by design array method like I.push(arr, data) doesn't freeze data

### ISSUE THREAD

**Issue by bitinn** [aearly/icepick#13]
I discover this when trying to modify an object with structure like `{ a: [ {b:1}, {b:2} ] }`.

The best way I can think of to push `{b:3}` onto `a` array is to:

```
var arr = I.push(store.a, {b:3});
I.assoc(store, 'a', arr);
```

Then I realize `{b:3}` isn't freezed in the process.

Am I doing this right? Is it by design?

(not that it's a problem, I can certainly `I.freeze` the data before `I.push`).

**Comment by aearly** [comment]
No, you're right -- the data should be frozen in this case.
