### ISSUE TITLE
Doc on github readme wrong lol

### ISSUE THREAD

**Issue by irisjay** [aearly/icepick#15]
Obvious mistakes:
//In getIn section
var coll = i.freeze([
  {a: 1},
  {b: 2}
]);

var result = i.getIn(coll, [1, "b"]); // 2

//In merge section
var defaults = {a: 1, c: {d: 1, e: [1, 2, 3], f: {g: 1}};
var obj = {c: {d: 2, e: [2], f: null};

var result1 = i.merge(defaults, obj); // {a: 1, c: {d: 2, e: [2]}, f: null}

var obj2 = {c: {d: 2}};
var result2 = i.merge(result1, obj2);

assert(result1 === result2); // true

**Comment by aearly** [comment]
What is wrong exactly?  Those are pulled from test cases, which work.

**Comment by irisjay** [comment]
Its just a small typo. In the merge section you missed a }
