### ISSUE TITLE
Documentation unclear about whether icepick adds methods to `Object.prototype`

### ISSUE THREAD

**Issue by danny-andrews** [aearly/icepick#19]
In the docs, it says `seamless-immutable is the most similar to icepick. Its main difference is that it adds more methods to the prototypes of objects`, but I was under the impression that icepick didn't add *any* methods to the prototypes of objects. If that's the case, we should delete the 'more' from above to make that clear.

**Comment by aearly** [comment]
Sure, I was thinking "more" in the context of "in addition to the existing methods" when I wrote that.  Feel free to submit a PR if you want. :)

**Comment by danny-andrews** [comment]
Didn't mean to sound persnickety, but adding/modifying built-in methods was a game-changer for me (and I presume many others as well) and I think the fact that this library doesn't do that is a major strength, so I wanted to make sure that was emphasized! Thanks!

**Comment by aearly** [comment]
Thanks!  I'm glad you pointed out this point of confusion.
