### ISSUE TITLE
`assign` description incorrect?

### ISSUE THREAD

**Issue by tonovotny** [aearly/icepick#26]
Docs says that `assign` is `always returning a new, immutable object` which I believe is not true since https://github.com/aearly/icepick/pull/22

**Comment by aearly** [comment]
Yes, that is slightly incorrect now.  I'd be open to a PR that clarifies.

**Comment by tonovotny** [comment]
After some thinking I think it's enough (in the context of whole docs) to remove the part about "always new" object.

**Comment by aearly** [comment]
Fixed in #27
