### ISSUE TITLE
Uglify fails on 2.0 with RCA

### ISSUE THREAD

**Issue by Psykar** [aearly/icepick#33]
See https://github.com/Psykar/test-icepick-uglify

RCA transpiles to ES5 before it attempts to uglify, but seems it's falling over on some ES6 syntax. Installing `icepick@<2` does work, and I don't have the time to debug this further right now unfortunately, but the repro is pretty simple.

* `create-react-app test-icepick-uglify`
* `cd test-icepick-uglify`
* `yarn add icepick`
* Edit `src/App.js` to add an icepick import
* `yarn build`
```
yarn build v0.24.6
$ react-scripts build 
Creating an optimized production build...
Failed to compile.

static/js/main.fd1459b7.js from UglifyJs
Unexpected token: operator (>) [./~/icepick/icepick.js:16,0][static/js/main.fd1459b7.js:11521,25]

error Command failed with exit code 1.
```

Alternatively, clone https://github.com/Psykar/test-icepick-uglify then `yarn build` and you'll also see it :)

**Comment by aearly** [comment]
Looks like CRA doesn't use a version of uglify that supports ES6 yet: https://github.com/facebookincubator/create-react-app/issues/2108

In the meantime, you can use icepick@^1, there are no new features in 2.0,

**Comment by Psykar** [comment]
So they're uglifying before transpiling. Weird. I guess this can be closed then, not an issue on your end (and yeah ^1 works fine =)
