### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by odzb** [aearly/icepick#38]
Could you please add a LICENSE file with the full text of the MIT license and the copyright holder's name? It is needed to pass a legal review. Simply specifying that the license is "MIT" is not sufficient because it's not legally definable what EXACTLY does "MIT" mean.

Thanks a lot!

**Comment by aearly** [comment]
I would conjecture that since npm requires the license field to be a valid SPDX identifier, "MIT" is good enough, but IANAL so I've added one anyway.

**Comment by odzb** [comment]
Thanks a lot!
