### ISSUE TITLE
Version of Icepick that does not freeze

### ISSUE THREAD

**Issue by theojapa** [aearly/icepick#46]
I use Icepick on React/Redux projects for two main reasons:

1. deep freezing makes sure that I don't introduce hard-to-track-down bugs in which state is accidentally mutated.
2. use of the various helper functions that efficiently "update" state using structural sharing.

Typically, I deep freeze every slice in my Redux store. However, for some data-heavy apps, there's a performance hit for doing so. What would you think of a variant of Icepick (that could be used in production) that provide the same helper functions but skips the freezing?

**Comment by aearly** [comment]
Set `NODE_ENV=production` as an environment variable, and the `Object.freeze()` is skipped.

https://github.com/aearly/icepick/blob/master/icepick.js#L77-L85

**Comment by theojapa** [comment]
Nice! I missed that in the docs.
