### ISSUE TITLE
Add `chain` to enable chaining calls

### ISSUE THREAD

**Issue by jakubholynet** [aearly/icepick#6]
Hi Alexander, thank a lot for icepick!

As a great fan of functional programming, I am used to chaining functions like here:
```javascript
var _ = require("lodash");
// Transform [{name: Kirk, address: {country: Norway, city: Oslo}},...] to [Oslo,..]:
_.chain(crewMembers).map("address").filter({country: "Norway"}).map("city").value()
```
With icepick this quickly becomes difficult to read (as in old good Lisp) since I have to read it inside-out:
```javascript
i.map(
  i.filter(
    i.map(crewMembers, myMakeGetter("address"))
  myMakePredicate({country: "Norway"}))
myMakeGetter("city")
```
It would be great if Icepick supported chaining these operations for example in the same way that lodash does witch `chain` ... `value()`. 
Thank you!

**Comment by aearly** [comment]
I like the idea!  The chain could also be intelligent and only create the array copies it actually needs to with a chained `.map().filter().map()` etc. only creating one extra array.

Modern lisps have a threading macro ( `(->)` in clojure), to make those nested function calls more readable.  Mori has [`pipeline`](http://swannodette.github.io/mori/#pipeline) which gives similar behavior.  I'm also considering adding something like `pipeline`.

**Comment by jakubholynet** [comment]
Lovely! Thank you.

Of course the best solution would be to just use ClojureScript ;-)

--
Forget software. Strive to make an impact, deliver a valuable change.

(Vær så snill og hjelp meg med å forbedre norsken min – skriftlig og
muntlig. Takk!)

Jakub Holy
Solutions Engineer | +47 966 23 666
Iterate AS | www.iterate.no
The Lean Software Development Consultancy
- http://theholyjava.wordpress.com/ -
8. juni 2015 21:28 skrev "Alexander Early" <notifications@github.com>:

**Comment by rileyjshaw** [comment]
++
